routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


#Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
 
 

 
Route::get('locale/{locale}', function () {
  	$locale = \Request::segment(2); 
	\Session::put('locale', $locale);
	return redirect('/2');
});


 



//Route::get('/', 'FrontendController@index');
//Route::group(array('prefix' => '{locale}'), function () {
Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');



	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});
 


//Route::group(['prefix' => 'de', 'middleware' => 'adminLanguage'], function () {

	Route::group(['prefix' => 'admin', 'middleware' => ['auth' ]], function () {
	
		

	 
		Route::resource('user', 'UserController', ['except' => ['show']]);
		Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
		Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
		Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

		Route::resource('questions', 'QuestionsController');
		Route::post('question-sortable', 'QuestionsController@updateOrder');
		Route::resource('categories', 'CategoriesController');
		Route::post('categories-sortable', 'CategoriesController@updateOrder');

		Route::resource('quiz', 'QuizController');
		Route::post('quiz-sortable', 'QuizController@updateOrder');

		Route::resource('information', 'InformationController');
		Route::post('info-sortable', 'InformationController@updateOrder');
		Route::post('information/delete-image', 'InformationController@deleteImage');
		Route::post('info-details', 'InformationController@infoDetailsById');
		Route::post('addQuiz', 'InformationController@addQuiz');
		Route::post('get-info-desc-html', 'InformationController@getDescHtml');
	 
		Route::post('upload_image','InformationController@uploadImage')->name('upload');
		

		Route::match(['post', 'get'], 'explanatory-video', 'ExplanatoryVideoController@explanatoryVideo')->name('explanatoryVideo');
		Route::post('explanatory/upload-video', 'ExplanatoryVideoController@uploadVideo')->name('uploadVideo');

		Route::resource('video', 'ExplanatoryVideoController');
		/*Route::get('questions', function () {
		return view('questions.index');
	})->name('questions'); */
	});
//});
Route::post('user/store', 'FrontendController@userStore')->name('userStore');
Route::post('change-language', 'FrontendController@changeLanguage')->name('changeLanguage');
Route::post('question/user-type-details', 'FrontendController@userTypeDetails')->name('userTypeDetails');
Route::post('question/info-details', 'FrontendController@infoDetails')->name('infoDetails');

Route::post('information/get-quiz-details', 'FrontendController@getQuizDetails')->name('getQuizDetails');
Route::post('information/verify-quiz', 'FrontendController@verifyQuiz')->name('verifyQuiz');
Route::post('information/review', 'FrontendController@review')->name('review');
 

Route::post('information/get-more-information', 'FrontendController@getMoreInformation');

/*************route to terminal starts here ************* */
 Route::get('terminal', 'VisitorController@index')->name('terminal');


/*************route to terminal ends here ************* */
// "/" routes will be default language routes, and "/$prefix" routes will be routes for all other languages

 
	Route::get('/home', 'HomeController@index')->name('home');
	 Route::get('/', 'FrontendController@index');
	 Route::match(['post', 'get'], '/{lang}/{user_group}',  'FrontendController@indexCategories');
	 Route::match(['post', 'get'], '/{lang}',  'FrontendController@indexUserGroup');
	 Route::match(['post', 'get'], '/',  'FrontendController@indexLanguage');
	 

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white" data-image="{{ asset('material') }}/img/sidebar-3.jpg">
  <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
  <div class="logo">
    <a href="#" class="simple-text logo-normal">
      {{ __('TP Checkin Portal') }}
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('home') }}">
          <i class="material-icons">dashboard</i>
            <p>{{ __('common.dashboard') }}</p>
        </a>
      </li>
   <!--
      <li class="nav-item{{ $activePage == 'user' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('user.index') }}">
          <i class="material-icons">person</i>
          <span class="sidebar-normal"> {{ __('user.management') }} </span>
        </a>
      </li>
-->
    
      <li class="nav-item{{ $activePage == 'questions' ? ' active' : '' }}">
        <a class="nav-link"  data-toggle="collapse" href="#questionNav"   href="{{ route('questions.index') }}">
          <i class="material-icons">question_answer</i> 
          <p>{{ __('questions.management') }}  <b class="caret"></b></p>
        </a>
     
        <div class="collapse  {{ $activeMod == 'questions' ? ' show' : '' }}  " id="questionNav">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'questions' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('questions.index') }}">
                <span class="sidebar-mini">     <i class="material-icons">navigate_next</i> </span>
                <span class="sidebar-normal">{{ __('questions.questions') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'add_questions' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('questions.create') }}">
                <span class="sidebar-mini">   <i class="material-icons">navigate_next</i>  </span>
                <span class="sidebar-normal"> {{ __('questions.addQuestion') }} </span>
              </a>
            </li>
                

          </ul>
        </div>
      </li>

      <li class="nav-item{{ $activePage == 'categories' ? ' active' : '' }}">
        <a class="nav-link  "  data-toggle="collapse" href="#categoriesNav"   href="{{ route('categories.index') }}">
          <i class="material-icons">category</i> 
          <p>{{ __('categories.management') }}<b class="caret"></b></p>
        </a>
     
        <div class="collapse  {{ $activeMod == 'categories' ? ' show' : '' }}  " id="categoriesNav">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'categories' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('categories.index') }}">
                <span class="sidebar-mini">     <i class="material-icons">navigate_next</i> </span>
                <span class="sidebar-normal">{{ __('categories.categories') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'add_categories' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('categories.create') }}">
                <span class="sidebar-mini">   <i class="material-icons">navigate_next</i>  </span>
                <span class="sidebar-normal"> {{ __('categories.addCategory') }} </span>
              </a>
            </li>          
          </ul>
        </div>
      </li>


      <li class="nav-item{{ $activePage == 'info' ? ' active' : '' }}">
        <a class="nav-link"  data-toggle="collapse" href="#infoNav"   href="{{ route('information.index') }}">
          <i class="material-icons">info</i> 
          <p>{{ __('info.management') }}  <b class="caret"></b></p>
        </a>
          <div class="collapse  {{ $activeMod == 'info' ? ' show' : '' }}  " id="infoNav">
          <ul class="nav">
          <li class="nav-item{{ $activePage == 'information' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('information.index') }}">
                <span class="sidebar-mini">     <i class="material-icons">navigate_next</i> </span>
                <span class="sidebar-normal">{{ __('info.info') }} </span>
              </a>
            </li>
          <li class="nav-item{{ $activePage == 'add_info' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('information.create') }}">
                <span class="sidebar-mini">   <i class="material-icons">navigate_next</i>  </span>
                <span class="sidebar-normal"> {{ __('info.addInfo') }} </span>
              </a>
            </li>                      
           </ul>
        </div>
      </li>


      <li class="nav-item{{ $activePage == 'quiz' ? ' active' : '' }}">
        <a class="nav-link"  data-toggle="collapse" href="#quiznNav"   href="{{ route('quiz.index') }}">
          <i class="material-icons">question_answer</i> 
          <p>{{ __('quiz.management') }}  <b class="caret"></b></p>
        </a>
     <div class="collapse  {{ $activeMod == 'quiz' ? ' show' : '' }}  " id="quiznNav">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'quiz' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('quiz.index') }}">
                <span class="sidebar-mini">     <i class="material-icons">navigate_next</i> </span>
                <span class="sidebar-normal">{{ __('quiz.quiz') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'add_quiz' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('quiz.create') }}">
                <span class="sidebar-mini">   <i class="material-icons">navigate_next</i>  </span>
                <span class="sidebar-normal"> {{ __('quiz.addQuestion') }} </span>
              </a>
            </li> 
            <!--        
            <li class="nav-item{{ $activePage == 'explanatory_video' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('explanatoryVideo') }}">
                <span class="sidebar-mini">   <i class="material-icons">navigate_next</i>  </span>
                <span class="sidebar-normal"> {{ __('questions.exvideo') }} </span>
              </a>
            </li>   -->  
          </ul>
        </div>
      </li>
     
      <li class="nav-item{{ $activePage == 'video' ? ' active' : '' }}">
        <a class="nav-link"  data-toggle="collapse" href="#videoNav"   href="{{ route('video.index') }}">
          <i class="material-icons">video_library</i> 
          <p>{{ __('video.management') }}  <b class="caret"></b></p>
        </a>
     
        <div class="collapse  {{ $activeMod == 'video' ? ' show' : '' }}  " id="videoNav">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'video' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('video.index') }}">
                <span class="sidebar-mini">     <i class="material-icons">navigate_next</i> </span>
                <span class="sidebar-normal">{{ __('video.video') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'add_video' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('video.create') }}">
                <span class="sidebar-mini">   <i class="material-icons">navigate_next</i>  </span>
                <span class="sidebar-normal"> {{ __('video.addVideo') }} </span>
              </a>
            </li> 
                    
          
          </ul>
        </div>
      </li>

    </ul>
  </div>
</div>