routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


#Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
 
 

 
Route::get('locale/{locale}', function () {
  	$locale = \Request::segment(2); 
	\Session::put('locale', $locale);
	return redirect('/2');
});


 



//Route::get('/', 'FrontendController@index');
//Route::group(array('prefix' => '{locale}'), function () {
Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');



	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});
 


//Route::group(['prefix' => 'de', 'middleware' => 'adminLanguage'], function () {

	Route::group(['prefix' => 'admin', 'middleware' => ['auth' ]], function () {
	
		

	 
		Route::resource('user', 'UserController', ['except' => ['show']]);
		Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
		Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
		Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

		Route::resource('questions', 'QuestionsController');
		Route::post('question-sortable', 'QuestionsController@updateOrder');
		Route::resource('categories', 'CategoriesController');
		Route::post('categories-sortable', 'CategoriesController@updateOrder');

		Route::resource('quiz', 'QuizController');
		Route::post('quiz-sortable', 'QuizController@updateOrder');

		Route::resource('information', 'InformationController');
		Route::post('info-sortable', 'InformationController@updateOrder');
		Route::post('information/delete-image', 'InformationController@deleteImage');
		Route::post('info-details', 'InformationController@infoDetailsById');
		Route::post('addQuiz', 'InformationController@addQuiz');
		Route::post('get-info-desc-html', 'InformationController@getDescHtml');
	 
		Route::post('upload_image','InformationController@uploadImage')->name('upload');
		

		Route::match(['post', 'get'], 'explanatory-video', 'ExplanatoryVideoController@explanatoryVideo')->name('explanatoryVideo');
		Route::post('explanatory/upload-video', 'ExplanatoryVideoController@uploadVideo')->name('uploadVideo');

		Route::resource('video', 'ExplanatoryVideoController');
		/*Route::get('questions', function () {
		return view('questions.index');
	})->name('questions'); */
	});
//});
Route::post('user/store', 'FrontendController@userStore')->name('userStore');
Route::post('change-language', 'FrontendController@changeLanguage')->name('changeLanguage');
Route::post('question/user-type-details', 'FrontendController@userTypeDetails')->name('userTypeDetails');
Route::post('question/info-details', 'FrontendController@infoDetails')->name('infoDetails');

Route::post('information/get-quiz-details', 'FrontendController@getQuizDetails')->name('getQuizDetails');
Route::post('information/verify-quiz', 'FrontendController@verifyQuiz')->name('verifyQuiz');
Route::post('information/review', 'FrontendController@review')->name('review');
 

Route::post('information/get-more-information', 'FrontendController@getMoreInformation');

/*************route to terminal starts here ************* */
 Route::get('terminal', 'VisitorController@index')->name('terminal');


/*************route to terminal ends here ************* */
// "/" routes will be default language routes, and "/$prefix" routes will be routes for all other languages

 
	Route::get('/home', 'HomeController@index')->name('home');
	 Route::get('/', 'FrontendController@index');
	 Route::match(['post', 'get'], '/{lang}/{user_group}',  'FrontendController@indexCategories');
	 Route::match(['post', 'get'], '/{lang}',  'FrontendController@indexUserGroup');
	 Route::match(['post', 'get'], '/',  'FrontendController@indexLanguage');
	 

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Validation\Rule;
use App\Categories;
use App\category_lang;
use App\Questions;
use App\Answers;
use Validator;

class CategoriesController extends Controller
{
    
  
 /**
     * 

     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->getAllCategories();

        $types  = Categories::categoryTypes();
        return view('categories.index')->withCategories($categories)->withTypes($types);
    }

    /**
     * get all resource. // this function used for both frond end and backend
     *
     *  
     * @return \Illuminate\Http\Response
     */
    public function getAllCategories()
    {
        return  Categories::all()->sortBy("order_no");
    }

    /**
     * get all resource. // this function used for both frond end and backend
     *
     *  
     * @return \Illuminate\Http\Response
     */
    public function getAllCategoriesWithAnswers()
    {

        $result = [];
        $categories   =  Categories::all()->sortBy("order_no");

        foreach ($Categories  as $key =>    $question) {

            $answers = Categories::find($question->id);



            $result["$question->category"]  = $question;
            $result["$question->category"]["$question->id"] =        $answers->answers;
            //  $result['Categories']['ans'][] =  Answers::whereQuestionId($question->id)->get();
        }
        /*
echo '<pre>';
       print_r(   $result) ;
       exit();  */
        return       $categories;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types  = Categories::categoryTypes();
        return view('categories.create')->withTypes($types);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [ // <---
            'type' => 'required',
            'category_name' => 'required|unique:categories,name',
            'category_name_de'  => 'required|unique:category_lang,name',

        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $category = Categories::create([
            'type' =>  $request->type,
            'name' =>  $request->category_name,
            'order_no' => (Categories::count()) + 1,

        ]);
        $category->save();


        if ($category->id !== null) {
            category_lang::create([
                'category_id' =>  $category->id,
                'lang' => 'de',
                'name' =>  $request->category_name_de,
            ]);
        }
        return redirect('admin/categories')
            ->with('message', trans('categories.created_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        echo "show";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories   =  Categories::find($id);
        $types  = Categories::categoryTypes();
        $categoryLangDE = category_lang::where('category_id', $id)->where('lang', 'de')->get();
        if (!empty($categoryLangDE[0])) $categoryLangDE = $categoryLangDE[0];
        else {
            $categoryLangDE->name = '';
        }

        return view('categories.edit')->withCategories($categories)->withTypes($types)->withCategoryLangDE($categoryLangDE);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category_lang =   category_lang::where('category_id', $id)->where('lang', 'de')->first();
        if (!empty($category_lang)) {
          echo   $category_lang_id= $category_lang->id;
        }
        $validator = Validator::make($request->all(), [ // <---
            'type' => 'required',
            //'category_name' => 'required|unique:categories,name',
            'category_name' => 'required|unique:categories,name,' . $id,             
            'category_name_de'  => 'required|unique:category_lang,name,' .   $category_lang_id ,
        ]);



        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }
        $categories = Categories::find($id);
        $categories->name =  $request->category_name;
        $categories->type = $request->type;

        $categories->save();

        
        if (!empty($category_lang)) {
            $category_lang->name = $request->category_name_de;
            $category_lang->save();
        } else {
            category_lang::create([
                'category_id' =>   $id,
                'lang' => 'de',
                'name' =>  $request->category_name_de,
            ]);
        }
        return redirect('admin/categories')
            ->with('message', trans('categories.updated_success'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updateOrder(Request $request)
    {
        $categories = Categories::all();
        foreach ($categories as $category) {
            foreach ($request->order as $order) {
                if ($order['id'] == $category->id) {
                    $category->update(['order_no' => $order['position']]);
                }
            }
        }
        return response('Update Successfully.', 200);
    }




    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //                                                                                                                                                                                                              Answers::whereQuestionId($id)->delete();
        Categories::whereId($id)->delete();
        return response(['message' => trans('categories.delete_sucess')], 200);
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app', ['activePage' => 'add_categories', 'activeMod' => 'categories' , 'titlePage' => __('categories.management')])

@section('content')
<style>
  .form-control,
  .custom-select {
    width: 80% !important;
    display: inline;
  }

  .btn-link {
    padding: 2px;
  }
</style>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <form method="post" action="{{  route('categories.store')}}" autocomplete="off" class="form-horizontal">
          @csrf
          @method('post')
          <div class="card ">
            <div class="card-header card-header-primary">
              <h4 class="card-title">{{ __('categories.addCategory') }}</h4>
              <p class="card-category">{{ __('categories.quiz_information') }}</p>
            </div>
            <div class="card-body ">
              @if (session('status'))
              <div class="row">
                <div class="col-sm-12">
                  <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <i class="material-icons">close</i>
                    </button>
                    <span> {{ session('status') }}</span>
                  </div>
                </div>
              </div>
              @endif

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('categories.type') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('type') ? ' has-danger' : '' }}">
                    <select name="type" class="  browser-default custom-select">  
                    <option value="">{{ __('common.select_type') }}</option>
                    @foreach( $types as $key => $type)
                      <option value="{{$key}}">{{$type }}</option>
                      @endforeach                    
                
                    </select>

                    @if ($errors->has('type'))
                    <br><span id="type-error" class="error text-danger" for="input-type">{{ $errors->first('type') }}</span>
                    @endif
                  </div>
                </div>
              </div>


           

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('categories.name') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('category_name') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('category_name') ? ' is-invalid' : '' }}" name="category_name" id="input-question" type="text" placeholder="{{ __('categories.name') }}" value="{{ old('category_name' ) }}" aria-required="true" />
                    @if ($errors->has('category_name'))
                    <br><span id="question-error" class="error text-danger" for="input-question">{{ $errors->first('category_name') }}</span>
                    @endif
                  </div>
                </div>
              </div>
               
             
              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('categories.name_de') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('category_name_de') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('category_name_de') ? ' is-invalid' : '' }}" name="category_name_de" id="input-category_name_de" type="text" placeholder="{{ __('categories.name_de') }}" value="{{ old('category_name_de' ) }}" aria-required="true" />
                    @if ($errors->has('category_name_de'))
                    <br><span id="category_name_de-error" class="error text-danger" for="input-category_name_de">{{ $errors->first('category_name_de') }}</span>
                    @endif
                  </div>
                </div>
              </div>

              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>


@endsection
@push('js')

<script>
  jQuery(document).ready(function() {
 
 
    
  });
</script>
@endpush

resources/views/categories/edit.blade.php
@extends('layouts.app', ['activePage' => 'categories', 'activeMod' => 'categories' , 'titlePage' => __('categories.management')])

@section('content')
<style>
  .form-control,
  .custom-select {
    width: 80% !important;
    display: inline;
  }

  .btn-link {
    padding: 2px;
  }
</style>

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{  route('categories.update',$categories->id)}}" autocomplete="off" class="form-horizontal">
          @csrf
          @method('PUT')
          <div class="card ">
            <div class="card-header card-header-primary">
              <h4 class="card-title">{{ __('categories.updateCategory') }}</h4>
              <p class="card-category">{{ __('categories.quiz_information') }}</p>
            </div>
            <div class="card-body ">
              @if (session('status'))
              <div class="row">
                <div class="col-sm-12">
                  <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <i class="material-icons">close</i>
                    </button>
                    <span> {{ session('status') }}</span>
                  </div>
                </div>
              </div>
              @endif

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('categories.type') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('category') ? ' has-danger' : '' }}">
                    <select name="type" class="  browser-default custom-select">  
                    <option value="">{{ __('common.select_type') }}</option>                   
                      @foreach( $types as $key => $type)
                      <option value="{{$key}}" @if($key  == $categories->type )selected @endif>{{$type }}</option>
                      @endforeach  
                    </select>
                    @if ($errors->has('type'))
                    <br><span id="type-error" class="error text-danger" for="input-type">{{ $errors->first('type') }}</span>
                    @endif
                  </div>
                </div>
              </div>

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('categories.name') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('category') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('category') ? ' is-invalid' : '' }}" name="category_name" id="input-category" type="text" placeholder="{{ __('categories.name') }}" value="{{ old('category_name'  , $categories->name) }}" aria-required="true" />
                    @if ($errors->has('category_name'))
                    <br><span id="category-error" class="error text-danger" for="input-category">{{ $errors->first('category_name') }}</span>
                    @endif
                  </div>
                </div>
              </div>
               
              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('categories.name_de') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('category_name_de') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('category_name_de') ? ' is-invalid' : '' }}" name="category_name_de" id="input-category_name_de" type="text" placeholder="{{ __('categories.name_de') }}" value="{{ old('category_name_de'  , $categoryLangDE->name) }}" aria-required="true" />
                    @if ($errors->has('category_name_de'))
                    <br><span id="category_name_de-error" class="error text-danger" for="input-category_name_de">{{ $errors->first('category_name_de') }}</span>
                    @endif
                  </div>
                </div>
              </div>

 
              

              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>


@endsection
@push('js')

<script>
 
</script>
@endpush

resources/views/categories/index.blade.php
@extends('layouts.app', ['activePage' => 'categories', 'activeMod' => 'categories' , 'titlePage' => __('categories.management')])

@section('content')
<style>
  [type="search"] {
    border: 1px solid #ccc;
  }

  [name="datatable-question_length"] {
    border: 1px solid #ccc;
    padding: 5px;
  }

  table.dataTable.no-footer {

    border-bottom: 1px solid #ccc;
  }

  table.dataTable thead th,
  table.dataTable tfoot th {
    font-weight: 300;
  }
</style>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">{{__('categories.category')}}</h4>
            <p class="card-category">{{__('categories.subHead')}}</p>
          </div>
          <div class="card-body">
            @if (session('message'))
            <div class="row">
              <div class="col-sm-12">
                <div class="alert alert-success">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="material-icons">close</i>
                  </button>
                  <span> {{ session('message') }}</span>
                </div>
              </div>
            </div>
            @endif
            <div class="row">
              <div class="col-12 text-right">
                <a href="{{ route('categories.create') }}" class="btn btn-sm btn-primary"> {{__('categories.addCategory')}}</a>
              </div>
            </div>
            <div class="table-responsive">

              <table class="table   dataTable no-footer" id="datatable-category" role="grid" aria-describedby="datatable-editable_info">

                <thead class=" text-primary">
                  <tr role="row">
                    <th width="30px">#</th>
                    <th>{{ __('categories.type') }} </th>
                    <th >{{ __('categories.name') }} </th>
                    <th  >{{ __('categories.name_de') }} </th>
                    <th class="text-right"> {{ __('categories.actions') }} </th>
                  </tr>
                </thead>
                <tbody id="tablecontents">
                  @foreach($categories as $key => $category)
                  <tr class="row1" data-id="{{$category->id}}">
                    <td class="pl-3"><i class="fa fa-sort"></i></td>
                    <td> {{ $types[$category->type] }}</td>
                    <td>

                      {{ $category->name  }}
                    </td>

                    <td>


                      {{ $category->categoryLanguages[0]->name }}


                    </td>


                    <td class="td-actions text-right">
                      <a rel="tooltip" class="btn btn-success btn-link deleteBtn" href="#" data-queid="{{$category->id}}" data-original-title="" title="Delete">
                        <i class="material-icons">delete</i>
                        <div class="ripple-container"></div>
                      </a>
                      <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('categories.edit' ,$category->id ) }}" data-original-title="" title="">
                        <i class="material-icons">edit</i>
                        <div class="ripple-container"></div>
                      </a>
                    </td>
                  </tr>
                  @endforeach


                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    </div>
    <!-----------------Confirmation ---------->



    <!-- Modal -->
    <div class="modal fade" id="selectConfirmation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"> {{ __('categories.delete_title') }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {{ __('categories.delete_confirmation') }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('common.cancel_confirm_lbl') }}</button>
            <button type="button" class="btn btn-primary" id="selectConfirmBtn" data-question_id="">{{ __('common.confirm_lbl') }}</button>
          </div>
        </div>
      </div>
    </div>

    <!-----------------Confirmation End ---------->
    @endsection

    @push('js')

    <script>
      $(document).on("click", ".deleteBtn", function() {
        $('.alertDiv').remove();
        $('#selectConfirmation').modal();
        $('#selectConfirmBtn').attr('data-question_id', $(this).data('queid'));
      });

      $(document).on("click", "#selectConfirmBtn", function() {

        $('#selectConfirmation').modal();
        deleteCategory($(this).attr('data-question_id'));
      });


      function deleteCategory(Id) {
        var url = "{{ url('admin/categories') }}/" + Id;
        var token = $('meta[name="csrf-token"]').attr('content');
        $.ajax({
          type: "DELETE",
          dataType: "json",
          url: url,
          data: {
            _token: token
          },
          success: function(response) {
            $('#selectConfirmation').modal('toggle');
            $('.card-body').prepend(' <div class="row alertDiv">\
              <div class="col-sm-12">\
                <div class="alert alert-success">\
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">\
                    <i class="material-icons">close</i>\
                  </button>\
                  <span> ' + response.message + '</span>\
                </div>              </div>            </div>');

            $('tr[data-Id="' + Id + '"').remove();

          }
        });




        //sendOrderToServer();

      }
      $(function() {
        $("#datatable-category").DataTable({
          "aoColumnDefs": [{
              "bSortable": false,
              "aTargets": [4]
            },

          ],
          "language": {
            "sEmptyTable": "Keine Daten in der Tabelle vorhanden",
            "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
            "sInfoEmpty": "0 bis 0 von 0 Einträgen",
            "sInfoFiltered": "(gefiltert von _MAX_ Einträgen)",
            "sInfoPostFix": "",
            "sInfoThousands": ".",
            "sLengthMenu": "_MENU_ Einträge anzeigen",
            "sLoadingRecords": "Wird geladen...",
            "sProcessing": "Bitte warten...",
            "sSearch": "Suchen",
            "sZeroRecords": "Keine Einträge vorhanden.",
            "oPaginate": {
              "sFirst": "Erste",
              "sPrevious": "Zurück",
              "sNext": "Nächste",
              "sLast": "Letzte"
            },
            "oAria": {
              "sSortAscending": ": aktivieren, um Spalte aufsteigend zu sortieren",
              "sSortDescending": ": aktivieren, um Spalte absteigend zu sortieren"
            }
          }
        });

        $("#tablecontents").sortable({
          items: "tr",
          cursor: 'move',
          opacity: 0.6,
          update: function() {
            sendOrderToServer();
          }
        });

        function sendOrderToServer() {
          var order = [];
          var token = $('meta[name="csrf-token"]').attr('content');
          $('tr.row1').each(function(index, element) {
            order.push({
              id: $(this).attr('data-id'),
              position: index + 1
            });
          });

          $.ajax({
            type: "POST",
            dataType: "json",
            url: "{{ url('admin/categories-sortable') }}",
            data: {
              order: order,
              _token: token
            },
            success: function(response) {
              if (response.status == "success") {
                console.log(response);
              } else {
                console.log(response);
              }
            }
          });
        }
      });
    </script>
    @endpush