routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


#Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
 
 

 
Route::get('locale/{locale}', function () {
  	$locale = \Request::segment(2); 
	\Session::put('locale', $locale);
	return redirect('/2');
});


 



//Route::get('/', 'FrontendController@index');
//Route::group(array('prefix' => '{locale}'), function () {
Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');



	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});
 


//Route::group(['prefix' => 'de', 'middleware' => 'adminLanguage'], function () {

	Route::group(['prefix' => 'admin', 'middleware' => ['auth' ]], function () {
	
		

	 
		Route::resource('user', 'UserController', ['except' => ['show']]);
		Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
		Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
		Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

		Route::resource('questions', 'QuestionsController');
		Route::post('question-sortable', 'QuestionsController@updateOrder');
		Route::resource('categories', 'CategoriesController');
		Route::post('categories-sortable', 'CategoriesController@updateOrder');

		Route::resource('quiz', 'QuizController');
		Route::post('quiz-sortable', 'QuizController@updateOrder');

		Route::resource('information', 'InformationController');
		Route::post('info-sortable', 'InformationController@updateOrder');
		Route::post('information/delete-image', 'InformationController@deleteImage');
		Route::post('info-details', 'InformationController@infoDetailsById');
		Route::post('addQuiz', 'InformationController@addQuiz');
		Route::post('get-info-desc-html', 'InformationController@getDescHtml');
	 
		Route::post('upload_image','InformationController@uploadImage')->name('upload');
		

		Route::match(['post', 'get'], 'explanatory-video', 'ExplanatoryVideoController@explanatoryVideo')->name('explanatoryVideo');
		Route::post('explanatory/upload-video', 'ExplanatoryVideoController@uploadVideo')->name('uploadVideo');

		Route::resource('video', 'ExplanatoryVideoController');
		/*Route::get('questions', function () {
		return view('questions.index');
	})->name('questions'); */
	});
//});
Route::post('user/store', 'FrontendController@userStore')->name('userStore');
Route::post('change-language', 'FrontendController@changeLanguage')->name('changeLanguage');
Route::post('question/user-type-details', 'FrontendController@userTypeDetails')->name('userTypeDetails');
Route::post('question/info-details', 'FrontendController@infoDetails')->name('infoDetails');

Route::post('information/get-quiz-details', 'FrontendController@getQuizDetails')->name('getQuizDetails');
Route::post('information/verify-quiz', 'FrontendController@verifyQuiz')->name('verifyQuiz');
Route::post('information/review', 'FrontendController@review')->name('review');
 

Route::post('information/get-more-information', 'FrontendController@getMoreInformation');

/*************route to terminal starts here ************* */
 Route::get('terminal', 'VisitorController@index')->name('terminal');


/*************route to terminal ends here ************* */
// "/" routes will be default language routes, and "/$prefix" routes will be routes for all other languages

 
	Route::get('/home', 'HomeController@index')->name('home');
	 Route::get('/', 'FrontendController@index');
	 Route::match(['post', 'get'], '/{lang}/{user_group}',  'FrontendController@indexCategories');
	 Route::match(['post', 'get'], '/{lang}',  'FrontendController@indexUserGroup');
	 Route::match(['post', 'get'], '/',  'FrontendController@indexLanguage');
	 

app/Questions.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Questions extends Model
{
    use \App\Http\Traits\UsesUuid;



    // column name of key
    protected $primaryKey = 'id';

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',   'user_type',
        'question', 'question_de', 'order_no'

    ];
    /*
    public function Categories()
    {
        return $this->belongsTo('App\Categories', 'category', 'id' );
    }
*/

    public function answers()
    {
        return $this->hasMany('App\Answers', 'question_id', 'id');
    }


    public static function userTypes()
    {
        return [
            'visitor' => __('common.visitor'),
            'foreign_worker' =>  __('common.foreign_worker'),
            'truck_driver'  => __('common.truck_driver')
        ];
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categories;
use App\Answers;
use App\Questions;
use Validator;

class QuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = $this->getAllQuestions();
    
 
        return view('questions.index')->withQuestions($questions);
    }

    /**
     * get all resource. // this function used for both frond end and backend
     *
     *  
     * @return \Illuminate\Http\Response
     */
    public function getAllQuestions()
    {
        return  Questions::all()->sortBy("order_no");
    }

    /**
     * get all resource. // this function used for both frond end and backend
     *
     *  
     * @return \Illuminate\Http\Response
     */
    public function getAllQuestionsWithAnswers()
    {
        //        $questions   =  Questions::all()->sortBy("order_no"); 

        //echo '<pre>';
        $result = [];
        $questions   =  Questions::all()->sortBy("order_no");

        foreach ($questions  as $key =>    $question) {

            $answers = Questions::find($question->id);
            $result["$question->category"]  = $question;
            $result["$question->category"]["$question->id"] =        $answers->answers;
            //  $result['questions']['ans'][] =  Answers::whereQuestionId($question->id)->get();
        }
        /*
echo '<pre>';
       print_r(   $result) ;
       exit();  */
        return       $questions;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories  =  Categories::where('type' , 'question')->get();
        
        return view('questions.create')->withCategories($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
/*
        foreach ($request->answers['en']  as $ans_key => $answer) {
             print_r( $request->answers['de'][$ans_key])  ;
        }
exit();
*/
        $validator = Validator::make($request->all(), [  
            'question' => 'required',
            'question_de' => 'required'

        ]);



        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $question = Questions::create([
        
            'question' =>  $request->question,
            'question_de' =>  $request->question_de,
            'user_type' =>  $request->user_type,
            'order_no' => (Questions::count()) + 1,

        ]);
        $question->save();

        foreach ($request->answers['en']  as  $ans_key => $answer) {
            if ($answer  !== null) {
                $answer = Answers::create([
                    'question_id' => $question->id,
                    'answer' => $answer,
                    'answer_de' =>  $request->answers['de'][$ans_key]

                ]);
                $answer->save();
            }
        }
        return redirect('admin/questions')
            ->with('message', trans('questions.created_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        echo "show";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $questions   =  Questions::find($id);
        $answers     =  Answers::whereQuestionId($questions->id)->get();
        $answers_count     =  Answers::whereQuestionId($questions->id)->count();
        $categories  =  Categories::where('type' , 'question')->get();
        return view('questions.edit')->withQuestions($questions)->withAnswers($answers)->withCategories($categories)->withAnsCount($answers_count);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validator = Validator::make($request->all(), [ // <---
            'question' => 'required',
            'question_de'  => 'required',

        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }
        $questions = Questions::find($id);
       
        $questions->question = $request->question;
        $questions->question_de = $request->question_de;
        $questions->user_type =   $request->user_type;
        $questions->save();

        if (Answers::whereQuestionId($questions->id)->count() > 0) {
            Answers::whereQuestionId($questions->id)->delete();
        }

        if ($request->answers  !== null) {
            foreach ($request->answers['en']   as  $ans_key => $answer) {
                $answer = Answers::create([
                    'question_id' => $questions->id,
                    'answer' => $answer,   
                       'answer_de' =>  $request->answers['de'][$ans_key]

                ]);
                $answer->save();
            }
        }

        return redirect('admin/questions')
            ->with('message', trans('questions.updated_success'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updateOrder(Request $request)
    {
        $questions = Questions::all();

        foreach ($questions as $question) {
            foreach ($request->order as $order) {
                if ($order['id'] == $question->id) {
                    $question->update(['order_no' => $order['position']]);
                }
            }
        }

        return response('Update Successfully.', 200);
    }




    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       //                                                                                                                                                                                                              Answers::whereQuestionId($id)->delete();
        Questions::whereId($id)->delete();
        return response(['message' => trans('questions.delete_sucess')], 200);
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app', ['activePage' => 'add_questions', 'activeMod' => 'questions' , 'titlePage' => __('questions.management')])

@section('content')
<style>
  .form-control,
  .custom-select {
    width: 80% !important;
    display: inline;
  }

  .btn-link {
    padding: 2px;
  }

  .ansDiv {
    border: 1px solid #AAA;
    padding: 10px;
  }

  .ansDivApp {
    border: 1px solid #AAA;
    border-top: none;
    padding: 10px;
  }
</style>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <form method="post" action="{{  route('questions.store')}}" autocomplete="off" class="form-horizontal">
          @csrf
          @method('post')
          <div class="card ">
            <div class="card-header card-header-primary">
              <h4 class="card-title">{{ __('questions.addQuestion') }}</h4>
              <p class="card-category">{{ __('questions.questions_information') }}</p>
            </div>
            <div class="card-body ">
              @if (session('status'))
              <div class="row">
                <div class="col-sm-12">
                  <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <i class="material-icons">close</i>
                    </button>
                    <span> {{ session('status') }}</span>
                  </div>
                </div>
              </div>
              @endif



              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('questions.user_type') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('question') ? ' has-danger' : '' }}">
                    <select name="user_type" id="user_type" class="  browser-default custom-select">
                      @foreach(\App\Questions::userTypes() as $key => $category )
                      <option value="{{ $key }}">{{ $category }}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
              </div>


              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('questions.question_en') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('question') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('question') ? ' is-invalid' : '' }}" name="question" id="input-question" type="text" placeholder="{{ __('questions.question_en') }}" value="{{ old('question' ) }}" aria-required="true" />
                    @if ($errors->has('question'))
                    <br><span id="question-error" class="error text-danger" for="input-question">{{ $errors->first('question') }}</span>
                    @endif
                  </div>
                </div>
              </div>

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('questions.question_de') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('question_de') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('question_de') ? ' is-invalid' : '' }}" name="question_de" id="input-question_de" type="text" placeholder="{{ __('questions.question_de') }}" value="{{ old('question_de' ) }}" aria-required="true" />
                    @if ($errors->has('question_de'))
                    <br><span id="question_de-error" class="error text-danger" for="input-question_de">{{ $errors->first('question_de') }}</span>
                    @endif
                  </div>
                </div>
              </div>

              <div class="row answersCls">
                <label class="col-sm-2 col-form-label">{{ __('questions.possible_answers') }}</label>
                   <?php $en_var = "en" ; ?>
                <div class="col-sm-7 inc ansDiv">
                  <div class=" controls form-group{{ $errors->has('answers') ? ' has-danger' : '' }}">
                    <input class=" form-control{{ $errors->has('answers') ? ' is-invalid' : '' }}" name="answers[{{$en_var}}][]" id="input-answers" type="text" placeholder="{{ __('questions.answer_en') }}" value="{{ old('answers.en.0' ) }}" />
                    <br>
                    <input class=" form-control{{ $errors->has('answers_de') ? ' is-invalid' : '' }}" name="answers[de][]" id="input-answers-de" type="text" placeholder="{{ __('questions.answer_de') }}" value="{{ old('answers.de.0' ) }}" />
                    <a rel="tooltip" class="btn btn-success btn-link" href="javascript:void(0);" data-original-title="" id="append" title="Add More Answers">
                      <i class="material-icons">add_circle</i>
                      <div class="ripple-container"></div>
                    </a>
                  </div>
                </div>     


                <!--
                  <div class="col-md-1 text-sm-left ">
                  <a rel="tooltip" class="btn btn-success btn-link" href="javascript:void(0);" data-original-title="" id="append"  title="Add More Answers">
                        <i class="material-icons">add_circle</i>  
                        <div class="ripple-container"></div>
                      </a>
                  </div>-->
              </div>
              <?php

             
              if ((old('answers')  !== null)) {
                foreach (old('answers')['en']  as $key => $val) {
                  if ($key != 0) {
                    $val_de =  old('answers')['de'][$key] ;
              ?>
                    <div class="row  answerApp">
                      <label class="col-sm-2 col-form-label"> </label>
                      <div class="col-sm-7   ">
                        <div class="controls form-group ">
                          <input class="form-control" type="text" name="answers[en][]" placeholder="{{ __('questions.answer_en') }}" value="{{$val}}"><br>
                          <input class="form-control" type="text" name="answers[de][]" placeholder="{{ __('questions.answer_de') }}" value="{{$val_de}}">
                          <a rel="tooltip" data-del-count="{{$key}}" class="btn btn-danger btn-link remove_this " href="javascript:void(0);" data-original-title="" title="">
                            <i class="material-icons">delete_forever</i>
                            <div class="ripple-container"></div>
                          </a> </div>
                      </div>
                    </div>

              <?php
                  }
                }
              }
              ?>


              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>


@endsection
@push('js')

<script>
  jQuery(document).ready(function() {
    var answersCnt = 1; var de_var = "de"; var en_var = "en";
     var en_placeholder = "{{ __('questions.answer_en') }}";
     var de_placeholder = "{{ __('questions.answer_de') }}";
    jQuery(document).on('click', '#append', function(e) {
      answersCnt++;


      e.preventDefault();
      var html = ' <div class="row  answerApp "><label class="col-sm-2 col-form-label"> </label>\
                      <div class="col-sm-7  ansDivApp "><div class="controls form-group ">\
                <input class="form-control" type="text" name="answers['+en_var+'][]" placeholder="'+en_placeholder+'">\    <input class="form-control" type="text" name="answers['+de_var+'][]" placeholder="'+de_placeholder+'">\
                <a rel="tooltip" data-del-count="' + answersCnt + '" class="btn btn-danger btn-link remove_this " href="javascript:void(0);" data-original-title="" title="">\
                  <i class="material-icons">delete_forever</i><div class="ripple-container"></div></a>  </div> </div></div>';
      //  $(".answers").append();


      if ($('.answerApp').length > 0) {

        $(html).insertAfter(".answerApp:last");

      } else {
        $(html).insertAfter(".answersCls");
      }

      return false;
    });

    jQuery(document).on('click', '.remove_this', function() {


      jQuery(this).parent().parent().parent().remove();



      return false;
    });
    $("input[type=submit]").click(function(e) {
      e.preventDefault();
      $(this).next("[name=textbox]")
        .val(
          $.map($(".answersCls :text"), function(el) {
            return el.value
          }).join(",\n")
        )
    })
  });
</script>
@endpush

resources/views/questions/edit.blade.php
@extends('layouts.app', ['activePage' => 'questions', 'activeMod' => 'questions' , 'titlePage' => __('questions.management')])

@section('content')
<style>
  .form-control,
  .custom-select {
    width: 80% !important;
    display: inline;
  }

  .btn-link {
    padding: 2px;
  }

  .ansDiv {
    border: 1px solid #AAA;
    padding: 10px;
  }

  .ansDivApp {
    border: 1px solid #AAA;
    border-top: none;
    padding: 10px;
  }
</style>

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{  route('questions.update',$questions->id)}}" autocomplete="off" class="form-horizontal">
          @csrf
          @method('PUT')
          <div class="card ">
            <div class="card-header card-header-primary">
              <h4 class="card-title">{{ __('questions.updateQuestion') }}</h4>
              <p class="card-category">{{ __('questions.questions_information') }}</p>
            </div>
            <div class="card-body ">              @if (session('status'))
              <div class="row">
                <div class="col-sm-12">
                  <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <i class="material-icons">close</i>
                    </button>
                    <span> {{ session('status') }}</span>
                  </div>
                </div>
              </div>
              @endif


              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('questions.user_type') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('user_type') ? ' has-danger' : '' }}">


                    <select name="user_type" id="user_type" class="   browser-default custom-select   ">
                      @foreach(\App\Questions::userTypes() as $key => $category )
                      <option value="{{ $key }}" @if( $key==$questions->user_type ) selected @endif>{{ $category }}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
              </div>


              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('questions.question') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('question') ? ' has-danger' : '' }}">

                    <input class="form-control{{ $errors->has('question') ? ' is-invalid' : '' }}" name="question" id="input-question" type="text" placeholder="{{ __('Question') }}" value="{{ old('question'  , $questions->question ) }}" aria-required="true" />
                    @if ($errors->has('question'))
                    <br><span id="question-error" class="error text-danger" for="input-question">{{ $errors->first('question') }}</span>
                    @endif
                    
                  </div>
                </div>
              </div>

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('questions.question_de') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('question_de') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('question_de') ? ' is-invalid' : '' }}" name="question_de" id="input-question_de" type="text" placeholder="{{ __('questions.question_de') }}" value="{{ old('question_de'  , $questions->question_de ) }}" aria-required="true" />
                    @if ($errors->has('question_de'))
                    <br><span id="question_de-error" class="error text-danger" for="input-question_de">{{ $errors->first('question_de') }}</span>
                    @endif
                  </div>
                </div>
              </div>


              <?php

              if ($ansCount > 0) {
                foreach ($answers  as $key => $val) {

                  if ($key === 0) {  ?>
                    <div class="row answersCls">
                      <label class="col-sm-2 col-form-label">{{ __('questions.possible_answers') }}</label>
                      <div class="col-sm-7 inc ansDiv ">
                        <div class=" controls form-group{{ $errors->has('answers') ? ' has-danger' : '' }}">
                          <input class=" form-control{{ $errors->has('answers') ? ' is-invalid' : '' }}" name="answers[en][]" id="input-answers" type="text" placeholder="{{ __('questions.answer_en') }}" value="{{ old('answers.0' , $val->answer  ) }}" />
                          <br>
                    <input class=" form-control{{ $errors->has('answers_de') ? ' is-invalid' : '' }}" name="answers[de][]" id="input-answers-de" type="text" placeholder="{{ __('questions.answer_de') }}" value="{{ old('answers.de.0' , $val->answer_de ) }}" />
                 

                          <a rel="tooltip" class="btn btn-success btn-link" href="javascript:void(0);" data-original-title="" id="append" title="Add More Answers">
                            <i class="material-icons">add_circle</i>
                            <div class="ripple-container"></div>
                          </a>

                        </div>
                      </div>
                    </div>
                  <?php
                  } else {
                  ?>
                    <div class="row  answerApp">
                      <label class="col-sm-2 col-form-label"> </label>
                      <div class="col-sm-7  ansDivApp ">
                        <div class="controls form-group ">
                          <input class="form-control" type="text" name="answers[en][]" placeholder="Answer" value="{{$val->answer}}">
                          <br>
                    <input class=" form-control{{ $errors->has('answers_de') ? ' is-invalid' : '' }}" name="answers[de][]" id="input-answers-de" type="text" placeholder="{{ __('questions.answer_de') }}" value="{{$val->answer_de}}" />
                 

                          <a rel="tooltip" data-del-count="{{$key}}" class="btn btn-danger btn-link remove_this " href="javascript:void(0);" data-original-title="" title="">
                            <i class="material-icons">delete_forever</i>
                            <div class="ripple-container"></div>
                          </a> </div>
                      </div>
                    </div>

                <?php
                  }
                }
              } else { ?><div class="row answersCls">
                  <label class="col-sm-2 col-form-label">{{ __('questions.possible_answers') }}</label>
                  <div class="col-sm-7 inc ansDiv">
                    <div class=" controls form-group{{ $errors->has('answers') ? ' has-danger' : '' }}">
                      <input class=" form-control{{ $errors->has('answers') ? ' is-invalid' : '' }}" name="answers[en][]" id="input-answers" type="text" placeholder="{{ __('questions.answer_en') }}" value="{{ old('answers.en.0'   ) }}" />
                      <br>
                    <input class=" form-control{{ $errors->has('answers_de') ? ' is-invalid' : '' }}" name="answers[de][]" id="input-answers-de" type="text" placeholder="{{ __('questions.answer_de') }}" value="{{ old('answers.de.0' ) }}" />
                 

                      <a rel="tooltip" class="btn btn-success btn-link" href="javascript:void(0);" data-original-title="" id="append" title="Add More Answers">
                        <i class="material-icons">add_circle</i>
                        <div class="ripple-container"></div>
                      </a>

                    </div>
                  </div>
                <?php
              }
                ?>

                
                </div> <div class="card-footer ml-auto mr-auto">
                  <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                </div>
        </form>
      </div>
    </div>
  </div>
</div>


@endsection
@push('js')

<script>
  // Material Select Initialization
  $(document).ready(function() {
    $('.mdb-select').materialSelect();
  });
  jQuery(document).ready(function() {
    var answersCnt = 1;
    var answersCnt = 1; var de_var = "de"; var en_var = "en";
     var en_placeholder = "{{ __('questions.answer_en') }}";
     var de_placeholder = "{{ __('questions.answer_de') }}";
    jQuery(document).on('click', '#append', function(e) {
      answersCnt++;


      e.preventDefault();
      var html = ' <div class="row  answerApp "><label class="col-sm-2 col-form-label"> </label>\
                      <div class="col-sm-7  ansDivApp "><div class="controls form-group ">\
                <input class="form-control" type="text" name="answers['+en_var+'][]" placeholder="'+en_placeholder+'">\    <input class="form-control" type="text"  name="answers['+de_var+'][]" placeholder="'+de_placeholder+'">\
                <a rel="tooltip" data-del-count="' + answersCnt + '" class="btn btn-danger btn-link remove_this " href="javascript:void(0);" data-original-title="" title="">\
                  <i class="material-icons">delete_forever</i><div class="ripple-container"></div></a>  </div> </div></div>';
      //  $(".answers").append();


      if ($('.answerApp').length > 0) {

        $(html).insertAfter(".answerApp:last");

      } else {
        $(html).insertAfter(".answersCls");
      }

      return false;
    });

    jQuery(document).on('click', '.remove_this', function() {


      jQuery(this).parent().parent().parent().remove();



      return false;
    });
    $("input[type=submit]").click(function(e) {
      e.preventDefault();
      $(this).next("[name=textbox]")
        .val(
          $.map($(".answersCls :text"), function(el) {
            return el.value
          }).join(",\n")
        )
    })
  });
</script>
@endpush