routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


#Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
 
 

 
Route::get('locale/{locale}', function () {
  	$locale = \Request::segment(2); 
	\Session::put('locale', $locale);
	return redirect('/2');
});


 



//Route::get('/', 'FrontendController@index');
//Route::group(array('prefix' => '{locale}'), function () {
Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');



	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});
 


//Route::group(['prefix' => 'de', 'middleware' => 'adminLanguage'], function () {

	Route::group(['prefix' => 'admin', 'middleware' => ['auth' ]], function () {
	
		

	 
		Route::resource('user', 'UserController', ['except' => ['show']]);
		Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
		Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
		Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

		Route::resource('questions', 'QuestionsController');
		Route::post('question-sortable', 'QuestionsController@updateOrder');
		Route::resource('categories', 'CategoriesController');
		Route::post('categories-sortable', 'CategoriesController@updateOrder');

		Route::resource('quiz', 'QuizController');
		Route::post('quiz-sortable', 'QuizController@updateOrder');

		Route::resource('information', 'InformationController');
		Route::post('info-sortable', 'InformationController@updateOrder');
		Route::post('information/delete-image', 'InformationController@deleteImage');
		Route::post('info-details', 'InformationController@infoDetailsById');
		Route::post('addQuiz', 'InformationController@addQuiz');
		Route::post('get-info-desc-html', 'InformationController@getDescHtml');
	 
		Route::post('upload_image','InformationController@uploadImage')->name('upload');
		

		Route::match(['post', 'get'], 'explanatory-video', 'ExplanatoryVideoController@explanatoryVideo')->name('explanatoryVideo');
		Route::post('explanatory/upload-video', 'ExplanatoryVideoController@uploadVideo')->name('uploadVideo');

		Route::resource('video', 'ExplanatoryVideoController');
		/*Route::get('questions', function () {
		return view('questions.index');
	})->name('questions'); */
	});
//});
Route::post('user/store', 'FrontendController@userStore')->name('userStore');
Route::post('change-language', 'FrontendController@changeLanguage')->name('changeLanguage');
Route::post('question/user-type-details', 'FrontendController@userTypeDetails')->name('userTypeDetails');
Route::post('question/info-details', 'FrontendController@infoDetails')->name('infoDetails');

Route::post('information/get-quiz-details', 'FrontendController@getQuizDetails')->name('getQuizDetails');
Route::post('information/verify-quiz', 'FrontendController@verifyQuiz')->name('verifyQuiz');
Route::post('information/review', 'FrontendController@review')->name('review');
 

Route::post('information/get-more-information', 'FrontendController@getMoreInformation');

/*************route to terminal starts here ************* */
 Route::get('terminal', 'VisitorController@index')->name('terminal');


/*************route to terminal ends here ************* */
// "/" routes will be default language routes, and "/$prefix" routes will be routes for all other languages

 
	Route::get('/home', 'HomeController@index')->name('home');
	 Route::get('/', 'FrontendController@index');
	 Route::match(['post', 'get'], '/{lang}/{user_group}',  'FrontendController@indexCategories');
	 Route::match(['post', 'get'], '/{lang}',  'FrontendController@indexUserGroup');
	 Route::match(['post', 'get'], '/',  'FrontendController@indexLanguage');
	 

app/Quiz.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Quiz extends Model
{
    use \App\Http\Traits\UsesUuid;

    protected $table = 'quiz';

    // column name of key
    protected $primaryKey = 'id';

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'category_id', 'user_group' ,'question_de',
        'question', 'order_no', 'answer','parent_id'

    ];


    /**
     * timestamps
     *
     * @var bool
     */
    public $timestamps = false;

    public function Categories()
    {
        return $this->belongsTo('App\Categories', 'category_id', 'id');
    }

    
}

app/Http/Controllers/QuizController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categories;
use App\Answers;
use App\Quiz;
use Validator;
use App\Information;
use App\explanatoryVideo;

class QuizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $quiz = $this->getAllQuiz();

        return view('quiz.index')->withQuiz($quiz);
    }

    /**
     * get all resource. // this function used for both frond end and backend
     *
     *  
     * @return \Illuminate\Http\Response
     */
    public function getAllQuiz()
    {
        return  Quiz::whereParentId('0')->get()->sortBy("order_no");
    }

    /**
     * get all resource. // this function used for both frond end and backend
     *
     *  
     * @return \Illuminate\Http\Response
     */
    public function getAllQuizWithAnswers()
    {
        //        $quiz   =  Quiz::all()->sortBy("order_no"); 

        //echo '<pre>';




        $result = [];
        $quiz   =  Quiz::all()->sortBy("order_no");

        foreach ($quiz  as $key =>    $question) {

            $answers = Quiz::find($question->id);



            $result["$question->category"]  = $question;
            $result["$question->category"]["$question->id"] =        $answers->answers;
            //  $result['Quiz']['ans'][] =  Answers::whereQuestionId($question->id)->get();
        }
        /*
echo '<pre>';
       print_r(   $result) ;
       exit();  */
        return       $quiz;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories  =  Categories::whereIn('type', ['question', 'video'])->get();
        return view('quiz.create')->withCategories($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        echo '<pre>';

        print_r($request->answers);
        print_r($request->multi_answer_sel);

        Categories::whereIn('type', ['question', 'video'])->get();
        if ($request->multi_answers ==  1) {
            $validator = Validator::make($request->all(), [
                'category' => 'required',
                'user_group' => 'required',
                'question' => 'required',


            ]);
        } else {
            $validator = Validator::make($request->all(), [
                'category' => 'required',
                'user_group' => 'required',
                'question' => 'required',
                'answer'   => 'required'

            ]);
        }


        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }


        $info_count =    Information::where(['category_id' =>  $request->category,   'user_group' =>  $request->user_group])->count();
        $video_count =    explanatoryVideo::where(['category_id' =>  $request->category,   'user_group' =>  $request->user_group])->count();


        if ($info_count  == 0 &&  $video_count  == 0) {
            return redirect()->back()->withErrors(['no_infos' => trans('quiz.no_infos')])->withInput();
        } else {

            $question = Quiz::create([
                'category_id' =>  $request->category,
                'user_group' =>  $request->user_group,
                //'question_de' =>  $request->question_de,
                'question'    =>  $request->question,
                'answer'      =>  0,
                'parent_id'   =>  0,
                'order_no'    => (Quiz::count()) + 1,

            ]);
            $question->save();
            if ($request->multi_answers ==  1) {           

                $parent_id =  $question->id;
     
                foreach ($request->answers as $key => $m_qa) {
                    
                    $question_ma = Quiz::create([
                        'category_id' =>  $request->category,
                        'user_group'  =>  $request->user_group,
                        'question'    =>  $m_qa,
                        'answer'      =>  $request->multi_answer_sel[$key],
                        'parent_id'   =>     $parent_id

                    ]);
                    $question_ma->save();
                    
                }
            }  
        }
        return redirect('admin/quiz')
            ->with('message', trans('quiz.created_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        echo "show";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $quiz   =  Quiz::find($id);
        $quizMultiAns = Quiz::whereParentId($id)->get();

       
        $answers     =  Answers::whereQuestionId($quiz->id)->get();
        $answers_count     =  Answers::whereQuestionId($quiz->id)->count();
        $categories  =  Categories::whereIn('type', ['question', 'video'])->get();
        return view('quiz.edit')->withQuiz($quiz)->withquizMultiAns($quizMultiAns)->withAnswers($answers)->withCategories($categories)->withAnsCount($answers_count);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validator = Validator::make($request->all(), [ // <---
            'category' => 'required',
            'user_group' => 'required',
            // 'question_de' => 'required',
            'question' => 'required'

        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }
        $info_count =    Information::where(['category_id' =>  $request->category,   'user_group' =>  $request->user_group])->count();
        $video_count =    explanatoryVideo::where(['category_id' =>  $request->category,   'user_group' =>  $request->user_group])->count();


        if ($info_count  == 0 &&  $video_count  == 0) {
            return redirect()->back()->withErrors(['no_infos' => trans('quiz.no_infos')])->withInput();
        } else {
            $quiz = Quiz::find($id);
            $quiz->category_id =  $request->category;
            $quiz->user_group =   $request->user_group;
            //  $quiz->question_de = $request->question_de;
            $quiz->question = $request->question;
            $quiz->answer      =  $request->answer;
            $quiz->save();


            if ($request->multi_answers ==  1) {
               

                Quiz::whereParentId($id)->delete();            

                foreach ($request->answers as $key => $m_qa) {
             
                 if(  $m_qa != "") {
                        $question_ma = Quiz::create([
                            'category_id' =>  $request->category,
                            'user_group'  =>  $request->user_group,
                            'question'    =>  $m_qa,
                            'answer'      =>  $request->multi_answer_sel[$key],
                            'parent_id'   =>  $id
    
                        ]);
                        $question_ma->save(); 
                        }
                    }
               
                   
                  
            } else {
                Quiz::whereParentId($id)->delete();
               
            }
        }
        return redirect('admin/quiz')
            ->with('message', trans('quiz.updated_success'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updateOrder(Request $request)
    {
        $quiz = Quiz::all();



        foreach ($quiz as $question) {
            foreach ($request->order as $order) {
                if ($order['id'] == $question->id) {
                    $question->update(['order_no' => $order['position']]);
                }
            }
        }

        return response('Update Successfully.', 200);
    }




    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //                                                                                                                                                                                                              Answers::whereQuestionId($id)->delete();
        Quiz::whereId($id)->delete();
        return response(['message' => trans('Quiz.delete_sucess')], 200);
    }
}

resources/views/quiz/create.blade.php
@extends('layouts.app', ['activePage' => 'add_quiz', 'activeMod' => 'quiz' , 'titlePage' => __('quiz.management')])

@section('content')
<style>
  .form-control,
  .custom-select {
    width: 80% !important;
    display: inline;
  }

  .btn-link {
    padding: 2px;
  }
  .multiAnsSel{
    padding: 6px;
  }
</style>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <form method="post" action="{{  route('quiz.store')}}" autocomplete="off" class="form-horizontal">
          @csrf
          @method('post')
          <div class="card ">
            <div class="card-header card-header-primary">
              <h4 class="card-title">{{ __('quiz.addQuestion') }}</h4>
              <p class="card-category">{{ __('quiz.quiz_information') }}</p>
            </div>
            <div class="card-body ">
              @if (session('status'))
              <div class="row">
                <div class="col-sm-12">
                  <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <i class="material-icons">close</i>
                    </button>
                    <span> {{ session('status') }}</span>
                  </div>
                </div>
              </div>
              @endif

              @if ($errors->has('no_infos'))

              <div class="row">
                <div class="col-sm-12">
                  <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <i class="material-icons">close</i>
                    </button>
                    <span> {{ $errors->first('no_infos') }}</span>
                  </div>
                </div>
              </div>
              @endif
              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('questions.user_type') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('user_group') ? ' has-danger' : '' }}">

                    <select name="user_group" id="user_group" class="   browser-default custom-select   ">
                      <option value="">{{ __('common.select_user_group') }}</option>
                      @foreach(\App\Questions::userTypes() as $key => $category )
                      <option value="{{ $key }}" @if( $key==old('user_group' ) )selected @endif>{{ $category }}</option>
                      @endforeach
                    </select>
                    @if ($errors->has('user_group'))
                    <br><span id="user_group-error" class="error text-danger" for="input-user_group">{{ $errors->first('user_group') }}</span>
                    @endif
                  </div>
                </div>
              </div>
              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('quiz.category') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('question') ? ' has-danger' : '' }}">

                    <select name="category" class="  browser-default custom-select">
                      <option value="">{{ __('common.select_category') }}</option>
                      @foreach( $categories as $key => $category)
                      <option value="{{$category->id}}" @if( $category->id == old('category' ) )selected @endif >{{$category->name}}</option>
                      @endforeach
                    </select>
                    @if ($errors->has('category'))
                    <br><span id="category-error" class="error text-danger" for="input-category">{{ $errors->first('category') }}</span>
                    @endif
                  </div>
                </div>
              </div>

            <!--  <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('quiz.question_de') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('question') ? ' has-danger' : '' }}">

                    <input class="form-control{{ $errors->has('question_de') ? ' is-invalid' : '' }}" name="question_de" id="input-question-de" type="text" placeholder="{{ __('quiz.question_de') }}" value="{{ old('question_de' ) }}" aria-required="true" />
                    @if ($errors->has('question'))
                    <br><span id="question-error" class="error text-danger" for="input-question-de">{{ $errors->first('question_de') }}</span>
                    @endif
                  </div>
                </div>
              </div>-->
              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('quiz.question') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('question') ? ' has-danger' : '' }}">

                    <input class="form-control{{ $errors->has('question') ? ' is-invalid' : '' }}" name="question" id="input-question" type="text" placeholder="{{ __('quiz.question') }}" value="{{ old('question' ) }}" aria-required="true" />
                    @if ($errors->has('question'))
                    <br><span id="question-error" class="error text-danger" for="input-question">{{ $errors->first('question') }}</span>
                    @endif
                  </div>
                </div>
              </div>

              <!------------------>
              <div class="row multiAnsCls " >
                <label class="col-sm-2 col-form-label">{{ __('quiz.multi_answers') }}</label>
                <div class="col-sm-7   ">
                  <div>               
                      <input class="form-radio-input multi_answers_cls" type="radio" value="1" name="multi_answers">
                      <label for="answer1">Yes</label> &nbsp; &nbsp;            
                 
                      <input class="form-radio-input multi_answers_cls " type="radio" name="multi_answers" value="0" checked>
                      <label for="answer2">No</label>                  
                  </div>
                </div>
              </div>

              <!------------------>
              <div class="row multiAnswersCls" style="display:none;">
                <label class="col-sm-2 col-form-label">{{ __('questions.possible_answers') }}</label>
            
                <div class="col-sm-7 inc ansDiv">
                  <div class=" controls form-group{{ $errors->has('answers') ? ' has-danger' : '' }}">
                    <input class=" form-control{{ $errors->has('answers') ? ' is-invalid' : '' }}" name="answers[]" id="input-answers" type="text" placeholder="{{ __('questions.answer_de') }}" value="{{ old('answers.en.0' ) }}" />
                    <select class="multiAnsSel" name="multi_answer_sel[]"><option value="1">Yes</option><option value="0">No</option></select>
                      <a rel="tooltip" class="btn btn-success btn-link" href="javascript:void(0);" data-original-title="" id="append" title="Add More Answers">
                      <i class="material-icons">add_circle</i>
                      <div class="ripple-container"></div>
                    </a>
                  </div>
                </div>     
 
              </div>
              <!---------------------->

              <div class="row answersCls">
                <label class="col-sm-2 col-form-label">{{ __('quiz.answer') }}</label>
                <div class="col-sm-7 inc ">

                  <div>
                    <div class="form-group md-radio">
                      <input class="form-radio-input" id="answer1" type="radio" value="1" name="answer" checked>
                      <label for="answer1">Yes</label>
                    </div>
                    <div class="md-radio">
                      <input class="form-radio-input " id="answer2" type="radio" name="answer" value="0">
                      <label for="answer2">No</label>
                    </div>
                  </div>

                </div>
<!--
        
                  <div class="col-md-1 text-sm-left ">
                  <a rel="tooltip" class="btn btn-success btn-link" href="javascript:void(0);" data-original-title="" id="append"  title="Add More Answers">
                        <i class="material-icons">add_circle</i>  
                        <div class="ripple-container"></div>
                      </a>
                  </div> -->
              </div>



              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>


@endsection
@push('js')

<script>
  jQuery(document).ready(function() {

    /********************** */

    jQuery(document).on('click', '.multi_answers_cls', function() {
      if ($(this).val() == 1) {
        $('.multiAnswersCls').show();
        $('.answersCls').hide();
      }else{
        $('.multiAnswersCls').hide();
        $('.answersCls').show();
      }
    });
    /********************** */
    var answersCnt = 1;
    jQuery(document).on('click', '#append', function(e) {
      answersCnt++;


      e.preventDefault();
      var html = ' <div class="row  answerApp "><label class="col-sm-2 col-form-label"> </label>\
                      <div class="col-sm-7   "><div class="controls form-group ">\
                <input class="form-control" type="text" name="answers[]" placeholder="Antwort">\
               <select name="multi_answer_sel[]" class="multiAnsSel"><option value="1">Yes</option><option value="0">No</option></select>\
                  <a rel="tooltip" data-del-count="' + answersCnt + '" class="btn btn-danger btn-link remove_this " href="javascript:void(0);" data-original-title="" title="">\
                  <i class="material-icons">delete_forever</i><div class="ripple-container"></div></a>  </div> </div></div>';
      //  $(".answers").append();


      if ($('.answerApp').length > 0) {

        $(html).insertAfter(".answerApp:last");

      } else {
        $(html).insertAfter(".multiAnswersCls");
      }

      return false;
    });

    jQuery(document).on('click', '.remove_this', function() {


      jQuery(this).parent().parent().parent().remove();



      return false;
    });
    $("input[type=submit]").click(function(e) {
      e.preventDefault();
      $(this).next("[name=textbox]")
        .val(
          $.map($(".answersCls :text"), function(el) {
            return el.value
          }).join(",\n")
        )
    })
  });
</script>
@endpush